local def = {}

def.VERTEX_TYPE_OFFSET0_STEP2 = 1
def.VERTEX_TYPE_OFFSET2_STEP5 = 2
def.VERTEX_OFFSET = 0
def.VERTEX_STEP = 2
def.VERTEX_TYPE = def.VERTEX_TYPE_OFFSET0_STEP2
def.REVERSE_TEXTURE_T = true
def.MAX_INTERPOLATION = 5
def.PIVOT_TABLE_SIZE = 65
def.GOSA = 0.0001

def.LIVE2D_FORMAT_VERSION_V2_8_TEX_OPTION = 8
def.LIVE2D_FORMAT_VERSION_V2_10_SDK2 = 10
def.LIVE2D_FORMAT_VERSION_V2_11_SDK2_1 = 11
def.LIVE2D_FORMAT_VERSION_AVAILABLE = def.LIVE2D_FORMAT_VERSION_V2_11_SDK2_1
def.OBJECT_REF = 33

return def
